export type KpiType = "leading" | "lagging";
export type KpiStatus = "on-track" | "at-risk" | "off-track";

export type KPI = {
  id: string;
  name: string;
  description: string;
  type: KpiType;
  category: string;
  currentValue: number;
  previousValue: number;
  targetValue: number;
  unit: string;
  status: KpiStatus;
  owner: string;
  formula: string;
  dataSource: string;
  updateFrequency: "daily" | "weekly" | "monthly" | "quarterly";
  trend: "up" | "down" | "flat";
  trendIsGood: boolean;
  notes: string;
};

export const kpis: KPI[] = [
  {
    id: "k01",
    name: "Competitive Threat Score",
    description: "Composite score (0–100) measuring the aggregate competitive pressure from all tracked competitors based on signal volume, sentiment, and market moves.",
    type: "leading",
    category: "Competitive Intelligence",
    currentValue: 82,
    previousValue: 77,
    targetValue: 65,
    unit: "/100",
    status: "off-track",
    owner: "Product Strategy",
    formula: "Weighted average of (Signal Volume × 0.3) + (Negative Sentiment × 0.4) + (Market Move Severity × 0.3)",
    dataSource: "SignalOps ingestion pipeline",
    updateFrequency: "weekly",
    trend: "up",
    trendIsGood: false,
    notes: "Kong's AI Gateway launch and Gartner MQ movement are primary drivers of score increase this week."
  },
  {
    id: "k02",
    name: "Feature Gap Score",
    description: "Measure of IBM API Connect's feature parity deficit relative to the best-in-class score across all tracked competitors for each capability.",
    type: "leading",
    category: "Product",
    currentValue: 68,
    previousValue: 63,
    targetValue: 45,
    unit: "/100",
    status: "off-track",
    owner: "Product Management",
    formula: "Average of (Best Competitor Score − IBM Score) across all feature dimensions, normalised to 0–100",
    dataSource: "Feature scoring matrix (monthly review)",
    updateFrequency: "monthly",
    trend: "up",
    trendIsGood: false,
    notes: "AI gateway and semantic caching gaps are widening fastest. Developer portal gap holding steady."
  },
  {
    id: "k03",
    name: "Review Sentiment Delta",
    description: "Difference between IBM API Connect's average review sentiment score and the category average across G2, TrustRadius, and Gartner Peer Insights.",
    type: "lagging",
    category: "Brand",
    currentValue: -0.08,
    previousValue: -0.05,
    targetValue: 0.05,
    unit: "pts",
    status: "off-track",
    owner: "Customer Marketing",
    formula: "IBM Avg Sentiment Score − Category Avg Sentiment Score (normalised 0–1 scale)",
    dataSource: "G2, TrustRadius, Gartner PI (automated scraping)",
    updateFrequency: "weekly",
    trend: "down",
    trendIsGood: false,
    notes: "Recent negative reviews citing AI feature gap are pulling IBM's score below the category average."
  },
  {
    id: "k04",
    name: "Recommended Actions Open",
    description: "Number of open strategic action items generated by the intelligence platform requiring owner assignment or completion.",
    type: "leading",
    category: "Operations",
    currentValue: 10,
    previousValue: 7,
    targetValue: 5,
    unit: "items",
    status: "at-risk",
    owner: "Product Strategy",
    formula: "COUNT(actions WHERE status != 'completed')",
    dataSource: "SignalOps action tracker",
    updateFrequency: "daily",
    trend: "up",
    trendIsGood: false,
    notes: "3 new actions added this week from Kong AI Gateway launch signals. 2 from last week remain in backlog."
  },
  {
    id: "k05",
    name: "Weekly Signal Volume",
    description: "Total number of competitive intelligence signals ingested across all sources in the past 7 days.",
    type: "leading",
    category: "Competitive Intelligence",
    currentValue: 147,
    previousValue: 118,
    targetValue: 100,
    unit: "signals",
    status: "on-track",
    owner: "Market Intelligence",
    formula: "COUNT(signals) WHERE publishedAt >= NOW() - 7 DAYS",
    dataSource: "SignalOps ingestion pipeline",
    updateFrequency: "daily",
    trend: "up",
    trendIsGood: true,
    notes: "High signal volume driven by Kong KongSummit 2026 and Google Cloud Next announcements this week."
  },
  {
    id: "k06",
    name: "Share of Voice (Developer Community)",
    description: "IBM API Connect's percentage of developer discussion mentions vs. total API management vendor mentions in developer communities (Reddit, Stack Overflow, HN).",
    type: "lagging",
    category: "Brand",
    currentValue: 14,
    previousValue: 17,
    targetValue: 20,
    unit: "%",
    status: "off-track",
    owner: "Developer Relations",
    formula: "IBM API Connect Mentions / Total Category Mentions × 100",
    dataSource: "Mention monitoring (Reddit, Stack Overflow, HackerNews)",
    updateFrequency: "weekly",
    trend: "down",
    trendIsGood: false,
    notes: "Kong and Apigee are capturing developer mind-share. IBM's developer content output needs to increase."
  },
  {
    id: "k07",
    name: "Competitor Trial Conversion Mentions",
    description: "Number of signals indicating a prospect or customer comparing IBM API Connect during a trial evaluation with a competitor.",
    type: "leading",
    category: "Sales",
    currentValue: 23,
    previousValue: 19,
    targetValue: 15,
    unit: "mentions",
    status: "off-track",
    owner: "Sales Enablement",
    formula: "COUNT(signals) WHERE tags CONTAINS 'trial' OR 'evaluation' OR 'comparison'",
    dataSource: "SignalOps signal classification",
    updateFrequency: "weekly",
    trend: "up",
    trendIsGood: false,
    notes: "Rising evaluations primarily driven by Kong's '15-minute portal' free trial campaign targeting IBM customers."
  },
  {
    id: "k08",
    name: "Content Response Time (Days)",
    description: "Average number of days between a major competitor announcement and IBM's published content response (blog, social, counter-messaging).",
    type: "leading",
    category: "Marketing",
    currentValue: 18,
    previousValue: 22,
    targetValue: 7,
    unit: "days",
    status: "at-risk",
    owner: "Content Marketing",
    formula: "AVG(IBM Content Publish Date − Competitor Announcement Date) for major events",
    dataSource: "Content calendar + signal timestamps",
    updateFrequency: "monthly",
    trend: "down",
    trendIsGood: true,
    notes: "Improving but still well above target. Kong AI Gateway announcement from May 14 still without IBM response."
  },
  {
    id: "k09",
    name: "G2 Score vs Category Leader",
    description: "Gap between IBM API Connect's G2 composite score and the current G2 category leader (Kong at 4.6).",
    type: "lagging",
    category: "Brand",
    currentValue: -0.8,
    previousValue: -0.6,
    targetValue: -0.2,
    unit: "pts",
    status: "off-track",
    owner: "Customer Marketing",
    formula: "IBM G2 Score − Category Leader G2 Score",
    dataSource: "G2 (weekly automated check)",
    updateFrequency: "weekly",
    trend: "down",
    trendIsGood: false,
    notes: "IBM at 3.8, Kong at 4.6. 23 new negative IBM reviews this month citing AI feature gaps and portal UX."
  },
  {
    id: "k10",
    name: "Migration Mention Rate",
    description: "Rate of signals mentioning customer or prospect migration away from IBM API Connect to a competitor, per 100 total signals.",
    type: "lagging",
    category: "Customer Retention",
    currentValue: 8.4,
    previousValue: 6.1,
    targetValue: 3.0,
    unit: "per 100",
    status: "off-track",
    owner: "Customer Success",
    formula: "COUNT(signals with 'migration' tag) / COUNT(all signals) × 100",
    dataSource: "SignalOps signal classification",
    updateFrequency: "weekly",
    trend: "up",
    trendIsGood: false,
    notes: "Migration mentions up 38% this month. Deutsche Bank displacement by Kong is the highest-impact signal."
  },
  {
    id: "k11",
    name: "Partner Ecosystem Mentions",
    description: "Volume of signals referencing competitor system integrator partnerships, certifications, or channel programmes that IBM is not part of.",
    type: "leading",
    category: "Ecosystem",
    currentValue: 31,
    previousValue: 24,
    targetValue: 15,
    unit: "signals",
    status: "off-track",
    owner: "Partner Marketing",
    formula: "COUNT(signals) WHERE tags CONTAINS 'partner' OR 'SI' OR 'certification' OR 'ecosystem'",
    dataSource: "SignalOps signal classification",
    updateFrequency: "weekly",
    trend: "up",
    trendIsGood: false,
    notes: "Apigee's 40% SI partner growth and Kong Academy's 10,000 certified engineers are key drivers."
  },
  {
    id: "k12",
    name: "Analyst Mention Sentiment",
    description: "Net positive/negative ratio of IBM API Connect mentions in analyst reports, blogs, and peer review sites (Gartner, Forrester, IDC, G2, TrustRadius).",
    type: "lagging",
    category: "Brand",
    currentValue: 0.31,
    previousValue: 0.38,
    targetValue: 0.55,
    unit: "ratio",
    status: "off-track",
    owner: "Product Marketing",
    formula: "Positive Analyst Mentions / (Positive + Negative Analyst Mentions)",
    dataSource: "Analyst report monitoring + G2/TrustRadius/Gartner PI",
    updateFrequency: "monthly",
    trend: "down",
    trendIsGood: false,
    notes: "Gartner MQ movement (Kong entering Leaders) and Forrester Wave placing IBM lower on Vision are key detractors."
  }
];
